services:
  postgres:
    image: postgres:18.1
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql
    env_file: .env
    environment:
      - POSTGRES_USER=convex
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=convex_self_hosted
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U convex"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    # Change this to :${REV} if you want to pin to a specific version
    image: ghcr.io/get-convex/convex-backend:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - data:/convex/data
    env_file: .env
    environment:
      - ACTIONS_USER_TIMEOUT_SECS
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_S3_DISABLE_CHECKSUMS
      - AWS_S3_DISABLE_SSE
      - AWS_S3_FORCE_PATH_STYLE
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN:-http://127.0.0.1:${PORT:-3210}}
      - CONVEX_RELEASE_VERSION_DEV
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN:-http://127.0.0.1:${SITE_PROXY_PORT:-3211}}
      - DATABASE_URL
      - DISABLE_BEACON
      - DOCUMENT_RETENTION_DELAY=${DOCUMENT_RETENTION_DELAY:-172800}
      - DO_NOT_REQUIRE_SSL
      - INSTANCE_NAME=convex-self-hosted
      - INSTANCE_SECRET
      - MYSQL_URL
      - POSTGRES_URL=postgres://convex:${POSTGRES_PASSWORD}@postgres:5432/convex_self_hosted
      - REDACT_LOGS_TO_CLIENT
      - RUST_BACKTRACE
      - RUST_LOG=${RUST_LOG:-info}
      - S3_ENDPOINT_URL
      - S3_STORAGE_EXPORTS_BUCKET
      - S3_STORAGE_FILES_BUCKET
      - S3_STORAGE_MODULES_BUCKET
      - S3_STORAGE_SEARCH_BUCKET
      - S3_STORAGE_SNAPSHOT_IMPORTS_BUCKET

    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy

  dashboard:
    # Change this to :${REV} if you want to pin to a specific version
    image: ghcr.io/get-convex/convex-dashboard:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    env_file: .env
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:${PORT:-3210}}
      - CONVEX_BACKEND_URL=http://backend:3210
      - CONVEX_SELF_HOSTED_ADMIN_KEY=${CONVEX_SELF_HOSTED_ADMIN_KEY}
    depends_on:
      backend:
        condition: service_healthy

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config

volumes:
  data:
  caddy_data:
  caddy_config:
